### PR TITLE
Migrate to new compiler syntax

### LINKED ISSUE #7: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #7.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #7

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Needed by PR ( https://github.com/conda-forge/snzip-feedstock/pull/6 ).

**Comment by jakirkham** [comment]
Merging so we can get to using the new compilers here. Hope that is ok.

**Comment by rmax** [comment]
@jakirkham thanks!

**Pull request merged**
